### ISSUE TITLE
WorldGuard blocks block interactions in TotallyNotHockey

### ISSUE THREAD

**Issue by ghost** [TheDeathlyCow/modular-minigames#1]
TotallyNotHockey map doesn't work - we can't break blocks nor use lingering potions.
Video: https://www.youtube.com/watch?v=KNGW3jkMEHA

**Comment by ghost** [comment]
Not a plugin/datapack issue but you told me to create issues here so

**Comment by TheDeathlyCow** [comment]
Set `block-break` flag to ALLOW. Should be working; reopen if the issue persists.
